//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a page of type <see cref="StorePage"/>.
	/// </summary>
	public partial class StorePage : IWebPageFieldsSource, ISEOFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "K13Store.StorePage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// HotTipProducts.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> HotTipProducts { get; set; }


		/// <summary>
		/// SEOFieldsTitle.
		/// </summary>
		public string SEOFieldsTitle { get; set; }


		/// <summary>
		/// SEOFieldsDescription.
		/// </summary>
		public string SEOFieldsDescription { get; set; }


        /// <summary>
		/// SEOFieldsAllowSearchIndexing.
		/// </summary>
        public bool SEOFieldsAllowSearchIndexing { get; set; }
    }
}
