//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace K13Store
{
	/// <summary>
	/// Represents a content item of type <see cref="ProductSKU"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ProductSKU : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "K13Store.ProductSKU";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// SKUID.
		/// </summary>
		public int SKUID { get; set; }


		/// <summary>
		/// SKUName.
		/// </summary>
		public string SKUName { get; set; }


		/// <summary>
		/// SKUShortDescription.
		/// </summary>
		public string SKUShortDescription { get; set; }


		/// <summary>
		/// SKUDescription.
		/// </summary>
		public string SKUDescription { get; set; }


		/// <summary>
		/// SKUNumber.
		/// </summary>
		public string SKUNumber { get; set; }


		/// <summary>
		/// SKUEnabled.
		/// </summary>
		public bool SKUEnabled { get; set; }


		/// <summary>
		/// SKUTrackInventory.
		/// </summary>
		public string SKUTrackInventory { get; set; }


		/// <summary>
		/// SKUSellOnlyAvailable.
		/// </summary>
		public bool SKUSellOnlyAvailable { get; set; }


		/// <summary>
		/// SKUAvailableItems.
		/// </summary>
		public int SKUAvailableItems { get; set; }


		/// <summary>
		/// SKUReorderAt.
		/// </summary>
		public int SKUReorderAt { get; set; }


		/// <summary>
		/// SKUProductType.
		/// </summary>
		public string SKUProductType { get; set; }


		/// <summary>
		/// SKUNeedsShipping.
		/// </summary>
		public bool SKUNeedsShipping { get; set; }


		/// <summary>
		/// SKUMinItemsInOrder.
		/// </summary>
		public int SKUMinItemsInOrder { get; set; }


		/// <summary>
		/// SKUMaxItemsInOrder.
		/// </summary>
		public int SKUMaxItemsInOrder { get; set; }


		/// <summary>
		/// SKUInStoreFrom.
		/// </summary>
		public DateTime SKUInStoreFrom { get; set; }


		/// <summary>
		/// CustomFields.
		/// </summary>
		public string CustomFields { get; set; }


		/// <summary>
		/// ClassName.
		/// </summary>
		public string ClassName { get; set; }


		/// <summary>
		/// NodeAliasPath.
		/// </summary>
		public string NodeAliasPath { get; set; }


		/// <summary>
		/// NodeGUID.
		/// </summary>
		public Guid NodeGUID { get; set; }


		/// <summary>
		/// ProductVariants.
		/// </summary>
		public IEnumerable<ProductVariant> ProductVariants { get; set; }


		/// <summary>
		/// ProductImages.
		/// </summary>
		public IEnumerable<ProductImage> ProductImages { get; set; }


		/// <summary>
		/// PublicStatusDisplayName.
		/// </summary>
		public string PublicStatusDisplayName { get; set; }


		/// <summary>
		/// DepartmentDisplayName.
		/// </summary>
		public string DepartmentDisplayName { get; set; }


		/// <summary>
		/// ManufacturerDisplayName.
		/// </summary>
		public string ManufacturerDisplayName { get; set; }
	}
}