//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace K13Store
{
	/// <summary>
	/// Represents a content item of type <see cref="ProductVariant"/>.
	/// </summary>
	public partial class ProductVariant : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "K13Store.ProductVariant";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// SKUID.
		/// </summary>
		public int SKUID { get; set; }


		/// <summary>
		/// SKUName.
		/// </summary>
		public string SKUName { get; set; }


		/// <summary>
		/// SKUNumber.
		/// </summary>
		public string SKUNumber { get; set; }


		/// <summary>
		/// SKUAvailableItems.
		/// </summary>
		public int SKUAvailableItems { get; set; }


		/// <summary>
		/// SKUEnabled.
		/// </summary>
		public bool SKUEnabled { get; set; }
	}
}